### ISSUE TITLE
question regarding word2vec

### ISSUE THREAD

**Issue by Mahmedturk** [eliorc/node2vec#48]
hi,

i am confused about wod2vec part in node2vec. As there are different pre-trained models of word2vec available, such as generic English and Pubmed models. Which pre-trained model of word2vec has been used in this experiment?

**Comment by eliorc** [comment]
Word2Vec is an algorithm - the pretrained models you are talking about are models generated using the Word2Vec algorithm in order to create embeddings.

So just like Pubmed word2vec embeddings were created by doing `PubMed Text -> Word2Vec Algorithm -> PubMed Word2Vec embeddings`, the Node2Vec algorithm is something like `Graph -> Node2Vec (generate walks from graph and input them to Word2Vec) -> Node embeddings`
