### ISSUE TITLE
generating node representation vector for individual nodes after embedding

### ISSUE THREAD

**Issue by amjass12** [eliorc/node2vec#57]
Hi!

I am using node2vec to generate node representation vectors after a random walk. I am working on an adjacency matrix where i want to randomly add or take away 1's and 0's to see how connectivity of the graph changes and then what the resulting node representation vector looks like. 

I run the random walk and then fit the model as follows:

```
from node2vec import Node2Vec
node2vec = Node2Vec(nx_graph, dimensions=128, walk_length=30, num_walks=50, workers=1, seed=30)
#fit
model = node2vec.fit(window=5, min_count=1, batch_words=4)
```

I can now use each node representation vector:
`model.wv('nodex')`

Now I want to edit the adjacency matrix- add or remove a random set of nodes (say 5 for example) and see how the vectors for these 5 nodes change. After changing connections on matrix

`nx.from_adjacency_matrix - etc`

However, I now have to re-run the walk and the model to see how node representation vector has changed..
This is computationally very slow - is there a way of keeping the node vectors from the original model and only finding how the nodes that I have changed in the adjacency matrix have changed for their node representation vector?? i hope this makes sense.. thank you.

**Comment by eliorc** [comment]
Hi @amjass12 

This is not possible because of the way the algorithm is designed. The output embeddings are dependent on the random walks generated, the random walks are dependent on the adjancency matrix. So if you make a change to that matrix, you basically can't guarantee the validity of the walks, so you have to randomly walk again. With a lot of effort I believe you can "hack" your way through this by calculating which walks are affected by the changes and only walking again from nodes that are affected... But that would take much work

**Comment by amjass12** [comment]
Hi @eliorc 

thank you for this detailed explanation! appreciate it :) the latter part is indeed more time consuming but might actually still be a good idea!
