### ISSUE TITLE
How would you update a model

### ISSUE THREAD

**Issue by loginn** [eliorc/node2vec#6]
I have a fairly large dataset (lower end of 1M nodes in a graph) with new nodes being added possibly every day or so.
I can save the graph and update it then run the Node2Vec again on the whole thing but I'd rather avoid having to do that because it takes a while. Is there a way to generate an embedding for a new node in the graph without running the Node2Vec over the whole graph ?

**Comment by eliorc** [comment]
An essential part of the node2vec algorithm is the walk generation, where a random walk is started from nodes in the graph.
If you trained a model on a specific graph and want to resume it after adding more nodes you essentially invalidate all the random walks that could have potentially touch the new nodes.

So to answer you question, this actually can't be done because of the nature of the algorithm rather than the implementation

**Comment by loginn** [comment]
Makes sense.
Thanks.
