### ISSUE TITLE
There may be a small problem with the walking length.

### ISSUE THREAD

**Issue by ecjtu-YangkaiLin** [eliorc/node2vec#86]
First of all, thank to the author for this wonderful work. 

In node2vec/parallel.py, line 49: ```while len(walk) < walk_length```. This seems to be an error, because in line 40, ```walk = [source]``` means that the first element is the source node. So there will be 1 less random walk.

Therefore, I think the correct writing should be ```while len(walk) <= walk_length```.

**Comment by eliorc** [comment]
Can you provide an example when this is wrong?

The walk starts with `[source]` and is of length 1 - this means that if you set length 1 all the walks will only have the source, and this is expected.

If you set it to 3, it will be `[source, node_a, node_b]`. But in your suggestion if you will have it as `while len(walk) <= walk_length` what will happen, is that on the third iteration, the requirement will still be met (`len([source, node_a, node_b]) <= 3`) and it will result in walks being `[source, node_a, node_b, node_c]` which creates walks of 4, instead of the chosen parameter 3

So I can't understand when `<=` is the right choice
